spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maxLifetime: 580000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
    database: mysql

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

gemini:
  api-key: ${API_KEY}


firebase:
  messaging:
    url:
      host: ${FIREBASE_HOST}
      path: ${FIREBASE_PATH}
      key: ${FIREBASE_KEY_JSON}
      credentials: ${FIREBASE_CREDENTIALS_URL}


auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}


